[package]
name = "rvoss"
version = "0.1.0"
edition = "2024"
description = "Voss-McCartney pink noise generation algorithm"
repository = "https://github.com/llwyd/rvoss"
license = "MIT"
readme = "README.md"

[dependencies]
rand = "0.10.0"
